# Generated by Django 4.2.4 on 2023-08-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestingEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('Date_joined', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=1)),
            ],
            options={
                'db_table': 'emptest',
            },
        ),
    ]
